name: ci
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install Composer deps (no dev ok too)
        run: composer install --no-interaction --prefer-dist --no-progress
      - name: PHP syntax check
        run: |
          find app bootstrap config database routes -type f -name "*.php" -print0 | xargs -0 -n1 -P4 php -l
