name: build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql, bcmath, ctype, tokenizer, dom, curl, fileinfo, json, xml, gd, openssl, zip
          coverage: none

      - name: Cache Composer vendor
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer deps (no scripts)
        run: composer install --no-ansi --no-interaction --no-progress --prefer-dist --no-scripts

      - name: PHP syntax lint
        run: |
          find app config database routes resources tests -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l
